server:
  port: 1010

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false # 不允许自己注册给自己
    fetchRegistry: false # 不允许拉去注册表
    serviceUrl: #服务的注册地址 http://localhost:1010/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/