eureka:
  client:
    serviceUrl: #注册地址
      defaultZone: http://localhost:1010/eureka/
    registry-fetch-interval-seconds: 10 # 抓取注册表快照的时间间隔
  instance:
    instance-id: www.course.com   #3.使用实例Id注册
    prefer-ip-address: true # 4.使用IP地址注册
server:
  port: 1070
spring:
  application:
    name: course-server    #2.使用服务名字注册
    #数据库配置
  datasource:
    url: jdbc:mysql:///hrm-course?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 199888yuan
    #德鲁伊连接池
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: soin1998
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8
        #扫描包路径
mybatis-plus:
  mapper-locations: classpath:org/soin/mapper/*Mapper.xml