eureka:
  client:
    serviceUrl: #注册地址
      defaultZone: http://localhost:1010/eureka/
    registry-fetch-interval-seconds: 10 # 抓取注册表快照的时间间隔
  instance:
    instance-id: www.zuul.com   #3.使用实例Id注册
    prefer-ip-address: true # 4.使用IP地址注册
server:
  port: 1020
spring:
  application:
    name: zuul-server  #2.使用服务名字注册

ribbon:
  ReadTimeout: 3000					#读取超时时间
  ConnectTimeout: 3000				#链接超时时间
  MaxAutoRetries: 1 				#重试机制：同一台实例最大重试次数
  MaxAutoRetriesNextServer: 1 		#重试负载均衡其他的实例最大重试次数
  OkToRetryOnAllOperations: false  	#是否所有操作都重试，因为针对post请求如果没做幂等处理可能会造成数据多次添加/修改

zuul:
  ribbon:
    eager-load.enabled: true  	# 饥饿加载
  prefix: "/hrm" #访问底层应用的统一前缀
  ignoredServices: "*"  #禁用掉使用浏览器通过服务名的方式访问服务
  routes:
    system-server: "/system/**"
    auth-server: "/auth/**"
    course-server: "/course/**"
    file-server: "/file/**"


