eureka:
  client:
    serviceUrl: #注册地址
      defaultZone: http://localhost:1010/eureka/
    registry-fetch-interval-seconds: 10 # 抓取注册表快照的时间间隔
  instance:
    instance-id: www.file.com   #3.使用实例Id注册
    prefer-ip-address: true # 4.使用IP地址注册
server:
  port: 1060
spring:
  application:
    name: file-server    #2.使用服务名字注册

#2.准备配置属性
file:
  alicloud:
    bucket-name: hrm-soin #上传空间bucket
    access-key: LTAI5tLDU3w9AqSo2efkf6gT #你的key
    secret-key: p9g1KU4WKHSsvu9rAFpQP3OrDlqmqH #你的秘钥
    endpoint: oss-cn-chengdu.aliyuncs.com  #上传端点